name: Run Selenium Cucumber Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  selenium-test
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
    - name: Setup Gradlew
      run: chmod +x gradlew
    - name: Execute Test
      run: ./gradlew cucumber
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
      
 
